language: ruby
rvm: 2.1.2
addons:
  postgresql: "9.3"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
notifications:
  email: false
  slack: task-planner:AlT8WOmrAl9wjPX9yDnygXNm
deploy:
  provider: heroku
  api_key:
    secure: Q6FTY/w0lyXt/OCfEK6gaedJI1vcPb/1SQF5i3TyDPl/Yzg8jUcJSNcGXxoRgSpO6V6g5o+92fc5bjLIoa45NhsmYvHnQAv3KIvslhKEgVLTdh+EBhq1njSWmh2XR4Mtfnf5yY0qEX+aDsseCllxJbCJWeiPxeC2MkNxSo+XMXE=
  app: task-planner
  run: "rake db:migrate"
