default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: catchup-web-dev

test:
  <<: *default
  database: catchup-web-test

production:
  <<: *default
  database: catchup-web-prod
