default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: task-planner-dev

test:
  <<: *default
  database: task-planner-test

production:
  <<: *default
  database: task-planner-prod
